# -*- coding: utf-8 -*-
"""Design A Bot Using AIML

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y5U-_3weL_gY0rt7drICjy2FEyhCWEGi
"""

pip install aiml

pip install python-aiml

pip install requests

pip install lxml

pip install pyts

pip install beautifulsoup4

import aiml

# Create the kernel
kernel = aiml.Kernel()

# Load AIML files
kernel.learn("simple_bot.aiml")
while True:
    user_input = input("You: ").upper()  # Convert input to uppercase
    bot_response = kernel.respond(user_input)
    print("Bot:", bot_response)