# -*- coding: utf-8 -*-
"""Design An Expert System Using AIML

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10-WkXGXOtVpSJevAH6zPXpNrJ1KyPv7Z
"""

pip install aiml

pip install python-aiml

pip install requests

pip install pyts

pip install lxml

pip install beautifulsoup4

import aiml

# Create a kernel
kernel = aiml.Kernel()

# Load AIML files
kernel.learn("std-startup.xml")
kernel.learn("basic_chat.aiml")  # Load your AIML files here

# Enter the conversation loop
while True:
    input_text = input(">Human: ")
    response = kernel.respond(input_text)
    print(">Bot: " + response)